# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://localhost:8081/api/ebook/add
Content-Type: application/json

{
    "isbn" : 4387,

    "title" : "Great Book",

    "year_published" : 2020,

    "book_type" : "EBOOK",
    "author" : {
    "id": 1
},
    "format" : "pdf",
    "size_mb" : 13

 }

###

POST http://localhost:8081/api/ebook/add
Content-Type: application/json

{
  "isbn" : 12345,

  "title" : "Book 2",

  "year_published" : 1990,

  "book_type" : "EBOOK",
  "author" : {
    "id": 2
  },
  "format" : "epub",
  "size_mb" : 20

}

###

POST http://localhost:8081/api/printbook/add
Content-Type: application/json

{
  "isbn" : 12,

  "title" : "Book 2",

  "year_published" : 1990,

  "book_type" : "PRINT_COPY",
  "author" : {
    "id": 2
  },
  "pages" : 1200,
  "weight" : 0.56

}

###

POST http://localhost:8081/api/printbook/add
Content-Type: application/json

{
  "isbn" : 120000,

  "title" : "Kniga",

  "year_published" : 1967,

  "book_type" : "PRINT_COPY",
  "author" : {
    "id": 3
  },
  "pages" : 120,
  "weight" : 0.26

}

###

GET http://localhost:8081/api/book


###
